### PR TITLE
Replace PSP cabinet art, two new variants

### PR DESCRIPTION
**Pull request by DisarmedSpy**
Includes new cabinet artwork for PSP using original PSP instead of PSP Go, two new variants (Default with Boxart and Media, Artful New) using new cabinet art as well as new controller images for one variant, and using 3D Boxart and Physical Media

### CODE REVIEW

**Comment by TheGrizzMD** [comment]
Sorry it took me so long to look at this in detail.  All of the controller images are nice, but this theme is already one of if not the largest es-de themes, so I don't think it would be a good idea to add an entire new set of images as it would further increase the size of the theme too much.  I like the concept of the PSP image and I think it is better to use one of the older model PSPs instead of the psp go or whatever it was called, but the image you used looks a bit blurry to me, and I see some kind of box to the right of the gradient in the middle: 
image

I don't mind adding a variant that uses a miximage instead of just the cover image, but I could see it looking a bit weird depending on how the user has configured their miximage settings.  Since the changes you are proposing are pretty substantial, it may be best to maintain your own version of the theme so everything is set the way you like it, but if you can create a higher quality PSP cabinet image and submit that I will merge it, and I would add a variant too as long as the variant name matches the rest of the theme.  Thanks for submitting this and take care.

**Comment by DisarmedSpy** [comment]
You're fine we all get busy! If I were to remove the new controller images
for now, as well as the new PSP image as honestly it was a very quick test
that I liked (If you'd like me to create a new PSP image, would you kinda
supply the background images minus the controller? My issue was getting the
gradient correct as you noted and I couldn't find the separate files)...
Would you merge just the "regular" variant for now, using your original
controller art after I create another pull request with those specific
changes? Also what would you propose the Variant name be if that is
acceptable in order to match the theme? I'm terrible with names.

**Comment by TheGrizzMD** [comment]
I will look for a template.

I can add the variant with something like "Default With 3D Boxes and Media", which is pretty close to what you suggested.  For some reason I thought you were using a miximage, but I see now that it is using two separate elements for each media type, sorry about that. I plan on trying it on my end and testing it.

**Comment by DisarmedSpy** [comment]
You're good! Take your time and just update me. :) You have my discord to
shoot me the template when you got that

**Comment by TheGrizzMD** [comment]
Here is a template for psp cabinet image. 
psp template

**Comment by TheGrizzMD** [comment]
Here is a blank template: 
psp template

**Pull request closed without merging**
